<?php

return [
    'plugin' => [
        'name' => 'Google Calendar API',
        'description' => 'Get Google Calendar Events on your site'
    ],
    'calendars' => [
        'menu_label' => 'Calendars'
    ],
    'images' => [
        'menu_label' => 'Images for Calendar Events'
    ],
    'fields' => [
        'summary' => 'summary',
        'description' => 'description',
        'last_sync_date' => 'Last Sync',
        'enabled' => 'Enabled',
        'label' => 'Label',
        'keywords' => 'Keywords',
        'image' => 'Image',
        'explain' => [
            'images_keywords' => 'Keywords used to match images to events',
            'images_label' => 'This is simply to help you identify the image'
        ]
    ],
    'api_fields' => [
        'project_name' => 'Google API Project Name',
        'client_id' => 'Client ID',
        'app_email' => 'Email Address',
        'gapi_key' => 'Private Key',
        'years_back' => 'Years back to sync',
        'years_forward' => 'Years forward to sync',
        'delete_old_events' => 'Delete old Events?',
        'explanation' => [
            'project_name' => 'The name you assigned to the project when you created it in Google API Console',
            'client_id' => 'You can find the Client ID on the project page in Google API Console',
            'app_email' => 'The email address generated by Google API Console',
            'gapi_key' => 'The private key file you downloaded from Google API Console',
            'years_back' => 'How many years ago should the system sync events from?',
            'years_forward' => 'How far into the future should the system sync events from (N.B. Repeating events may go on forever)?',
            'delete_old_events' => 'Delete events once they are too old to be synced?'
        ]

    ]
];